### ISSUE TITLE
Težave z medsebojno odvisnimi inputi

### ISSUE THREAD

**Issue by majorcek** [majorcek/MZR-knjiznicar#3]
Pozdravljeni!

V aplikaciji imam slider imenovan 'najvecje stevilo knjig izposoje' z Id = 'max_izposojenih', ki določa največje število knjig, ki si jih posameznik lahko izposodi (vsak uporabnik si lahko izposodi denimo največ 8 knjig). 
Rad bi, da bi se glede na ta input odprlo ustrezno število sliderjev (ali numericInput). Če izberemo, da je max_knjig = 5, bi se torej odprlo 5 sliderjev. S temi sliderji bi nastavili verjetnosti, da posameznik izbere eno, dve, tri, štiri ali pet knjig ( v splošnem 1:input$max_izposojenih).  Torej bi bili sliderji oblike sliderInput(Id =... , label = ... , min = 0, max = 1, value = 0, step = 0.01).
Obenem morajo medsebojno odvisni, da se seštejejo v 1, torej za slider2 nekaj takega: ....max = 1- input$slider1).
Na koncu pa je potrebno še to, da do vrednosti teh sliderjev lahko dostopam, ker bi jih rad uporabil za utezi v funkciji reactive(ustvari_novo_tabelo).

Da povzamem: 
- rad bi, da se prikaže samo toliko sliderjev, kolikor jih označimo s sliderjem max_izposojenih
- ti sliderji so medsebojno odvisni
- vrednosti sliderjov uporabimo, da naredimo vektor uteži.

Poskusil sem z conditionalPanel in renderUI, ampak zaenkrat se mi ni uspelo približati željam. 

Hvala za pomoč, 
Jaša

**Comment by jO-Osko** [comment]
Primer kako se naredi tak input lahko najdete na:
https://mastering-shiny.org/action-dynamic.html#creating-ui-with-code
Če dodate `uiOutput("izbor_knjig")` ja najlažje uporabiti knjižnico `purrr`, kjer potem tako zgenerirate preostale drsnike:

```
col_names <- reactive(paste0("knjige_input", seq_len(input$max_izposojenih)))
  
output$izbor_knjig <- output$col <- renderUI({
  map(col_names(), ~ sliderInput(.x , .x, min = 0, max = 1, value = 0, step = 0.01))
})
```

Do teh podatkov potem lahko dostopate z `input[["knjige_inputN"]]`, kjer je N številka knjige. 

Da pa se vse skupaj sešteje v 1 imate več možnosti: 
 - Uporabniku ne dovolite spreminjanja zadnejega drsnika, ki se avtomatsko nastavi iz prostanka ostalih (v resnici bi morali ob nastavitve prvega popraviti meje na vseh naslednjih (da ne gre vsota čez 1), enako ob drugem...)
 - Uporabnik nastavlja relativne uteži, ki se potem normirajo.

**Comment by majorcek** [comment]
Hvala
